clear;

% a malha e definida pela tupla (V,E,T)
%
% V : matriz de coordenadas, Nv por 3, onde Nv numero de vertices.
% E : lista de estrelas dos vertices. E{i}[j] = j-esimo triangulo incidente do vertice i
% T : matriz de triangulos. T(i,j) = j-esimo vertice do triangulo i



% inicializando corretamente
V = zeros(0,3);   % matriz vazia
E{1} = [];
T = zeros(0,3);

% insere um vertice na coordenada (0,0,0)
[V,E] = op_insere_vtc(V,E, [0,0,0]);

% insere mais vertices, desta vez, ao mesmo tempo
[V,E] = op_insere_vtc(V,E, [1,0,0; ...
                            2,0,0; ...
                            3,0,0; ...
                            0,1,0; ...
                            1,1,0; ...
                            2,1,0; ...
                            3,1,0; ...
                            0,2,0; ...
                            1,2,0; ...
                            2,2,0; ...
                            3,2,0; ...
                            0,3,0; ...
                            1,3,0; ...
                            2,3,0; ...
                            3,3,0]);

% insere varios triangulos
[E,T] = op_insere_tri(E,T, [1,2,6    ; ...
                            2,3,7    ; ...
                            3,4,8    ; ...
                            5,6,10   ; ...
                            6,7,11   ; ...
                            7,8,12   ; ...
                            9,10,14  ; ...
                            10,11,15 ; ...
                            11,12,16 ; ...
                            1,6,5    ; ...
                            2,7,6    ; ...
                            3,8,7    ; ...
                            5,10,9   ; ...
                            6,11,10  ; ...
                            7,12,11  ; ...
                            9,14,13  ; ...
                            10,15,14 ; ...
                            11,16,15]);



if (1) % coloque 1 imprimir a malha sem remocao

  trimesh(T,V(:,1),V(:,2),V(:,3),'FaceColor','interp','FaceLighting','phong','EdgeColor','black');

else

  % apaga alguns elementos
  [E,T] = op_remove_tri(E,T, [1:2:18]);

  % antes de plotar, coleta o lixo
  [V,E,T] = op_limpa_lixo(V,E,T);

  trimesh(T,V(:,1),V(:,2),V(:,3),'FaceColor','interp','FaceLighting','phong','EdgeColor','black');

end


% verificando se o coletor de lixo esta funcionando
if (0)

  % inicializando corretamente
  Vaux = zeros(0,3);   % matriz vazia
  Eaux{1} = [];
  Taux = zeros(0,3);

  [Vaux,Eaux] = op_insere_vtc(Vaux,Eaux, V);
  [Eaux,Taux] = op_insere_tri(Eaux,Taux, T);


end







